crabnebula-dev/cargo-packager

.github/workflows/check.yml
.gitignore
Cargo.lock
Cargo.toml
crates/config/Cargo.toml
crates/config_schema_generator/Cargo.toml
crates/packager/Cargo.toml
crates/updater/Cargo.toml
deny.toml
examples/dioxus/Cargo.toml
examples/egui/Cargo.toml
examples/slint/Cargo.toml
examples/tauri/Cargo.toml
examples/wry/Cargo.toml

This PR adds `cargo-deny` as a CI check to ensure our dependency tree only contains MIT/Apache-2.0 compatible licenses.
I also ran `cargo-deny` as part of setting this up ofc and it seems good except for 3 questions we have to answer:

feat: add cargo deny

---

.changes/fix-path-not-exist-error.md
crates/packager/src/package/app/mod.rs

This happens when bundling frameworks to `.app`, and frameworks does not exist with the provided path.
Add the following to `Cargo.toml` and run the packager to bundle `.app`,
```
[package.metadata.packager.macos]
frameworks = ["./somewhere/not/exist"]
```

fix(app): error of path not found in copy_dir

---

crates/packager/src/package/nsis/installer.nsi
crates/packager/src/package/nsis/mod.rs

port of https://github.com/tauri-apps/tauri/pull/8233

pref(nsis): calculate estimated size on build system

---

bindings/packager/nodejs/schema.json
crates/packager/schema.json
crates/packager/src/codesign/macos.rs
crates/packager/src/codesign/mod.rs
crates/packager/src/codesign/windows.rs
crates/packager/src/config/mod.rs
crates/packager/src/error.rs
crates/packager/src/package/app/mod.rs
crates/packager/src/package/dmg/mod.rs
crates/packager/src/package/nsis/mod.rs
crates/packager/src/package/wix/mod.rs

feat: add `config.windows.sign_command` to override signing command

---

.changes/glob-icons.md
crates/packager/schema.json
crates/packager/src/config/builder.rs
crates/packager/src/config/mod.rs
crates/packager/src/package/deb/mod.rs
crates/packager/src/package/wix/mod.rs
crates/packager/src/util.rs

This works for deb. Using the helpers method, it should be easy to port this to other target. But i don't have a mac for testing, and i should be able to get a Windows in a few weeks.
I know this code is a little shitty, i'm sorry. I never used `thiserror` crate before, so maybe it can be written with less lines.
Also, i was not able to convert a glob error to the error of this crate. Maybe i missing something here. And somehow, rust-anlyzer just stop working on this project, so a little painful to debug this.

Add glob support for icons field

---

.changes/fix-deb-launching.md
crates/packager/src/package/deb/mod.rs

This commit fixes #119 , which was caused due to previous patch, #118 
For some weird reason, order of `set_mode` matters a lot here. Even if we use `set_mode` just after `set_metadata`, there was same error.
Anyways, it should be fixed now.
Thank You!

Fix Debian package launching issue

---

.changes/priority-and-section.md
bindings/packager/nodejs/schema.json
bindings/packager/nodejs/src-ts/config.d.ts
crates/packager/schema.json
crates/packager/src/config/mod.rs
crates/packager/src/package/deb/mod.rs
examples/tauri/Cargo.toml

I am adding some necessary `config` options for debian packages.
These should be accessible via `[package.metadata.packager.deb]`
These changes are running perfectly fine on Arch Linux as well as Debian, but please, review carefully before approving.
Also, this is not complete yet, I will be adding certain options as well.

feat(deb): add `priority` and `section` options

---

.changes/fix-download-callbacks.md
bindings/updater/nodejs/index.d.ts
bindings/updater/nodejs/src/lib.rs

With ErrorStrategy CalleeHandled napi will give an additional parameter at position 0 into the callback which represents the error status of the function. Therefore when executing the `download` or `downloadInstall` functions the callbacks parameters will be shifted to the right by one and not match the typescript definitions.
When changing the ErrorStrategy to Fatal it will throw an exception instead which would be the desired behavior.
See [here](https://github.com/napi-rs/napi-rs/blob/69d2a75384dcf764e13200bc595e274b6db82263/crates/napi/src/threadsafe_function.rs#L82-L86)
```js
// Before fix (does not match the d.ts files):
availableUpdate.downloadAndInstall((errorThatWillBeAlwaysNull, chunkLength, contentLength) => { ... });
// After fix: …
```

Fix download callback parameter values and unblock functions

---

.changes/macos-signing-ordering.md
crates/packager/src/codesign/macos.rs
crates/packager/src/package/app/mod.rs

Sometimes code signing on macOS could fail since the ordering of files is not entirely deterministic. This fixes the issue by first sorting the files in a depth first order using a binary heap.

fix: sign more deeply nested files first on macOS

---

.changes/excluded-libs-appiamge.md
bindings/packager/nodejs/schema.json
bindings/packager/nodejs/src-ts/config.d.ts
crates/packager/schema.json
crates/packager/src/config/mod.rs
crates/packager/src/package/appimage/appimage
crates/packager/src/package/appimage/mod.rs

On Arch and maybe other distros it might be relevant to control the automatically included libs. This PR introduces a config option for .appimage files to exclude specific libraries.

feat: add config option to control excluded libs in AppImage

---

.changes/codesign-notarize-auth-config.md
Cargo.lock
crates/packager/src/codesign/macos.rs
crates/packager/src/config/mod.rs
crates/packager/src/package/app/mod.rs

When using the packager library, it doesn't make much sense to use environment variables (especially if you want to run the packager multiple times in parallel). This PR adds a config option that is only available programatically (serde(skip) is used so you can't inject it via the config file).

feat(packager): add codesign and notarization auth config options

---

.changes/add-pacman-support-resource-resolver.md
crates/resource-resolver/src/lib.rs

Add support for Pacman Packages in the Resource Resolver.
- closes #188 
Now, resource resolver can detect `Paman` format and also load resources for it.

fix(resource-resolver): Add pacman support for resource resolver, closes #188

---

.changes/app-bundle-cross-platform.md
.changes/package-output-struct-refactor.md
.prettierignore
Cargo.lock
crates/packager/Cargo.toml
crates/packager/src/error.rs
crates/packager/src/lib.rs
crates/packager/src/package/app/mod.rs
crates/packager/src/package/mod.rs
crates/packager/src/util.rs
deny.toml

This PR allows packaging the macOS app bundle on Linux and Windows hosts. Since we only copy assets to a .app folder, it is possible. codesign and notarization are skipped when not on a macOS host.

feat(packager): cross platform macOS app bundle packaging

---

.changes/binaries-dir.md
.changes/out-dir.md
Cargo.lock
bindings/packager/nodejs/schema.json
bindings/packager/nodejs/src-ts/config.d.ts
crates/packager/schema.json
crates/packager/src/cli/config.rs
crates/packager/src/cli/mod.rs
crates/packager/src/config/mod.rs

Currently cargo-packager expects the `Config::out_dir` value to contain the binaries to package AND uses it as the output directory. For Rust projects we manually detect the binaries output directory, so it's impossible to use a custom output directory for the packages.
This PR adds a `Config::binaries_dir` option so you can separate the package output directory and the relative-path-binaries source. With this change, it is possible to run `cargo packager ./out/packager` in a Rust project and it'll manually detect the binaries dir while using the provided output directory without crashing or failing to find the binaries.

feat(packager): config for binaries dir

---

.changes/enhance-shell-output.md
crates/packager/src/cli/mod.rs
crates/packager/src/lib.rs
crates/packager/src/package/mod.rs
crates/packager/src/shell.rs

It's hard to understand when e.g. a `cargo build` fails because we do not show its output without the `--verbose` flag. This PR changes the tracing event level to INFO so it's always available, and enhances the formatting to remove extra fields, dates, and log level.

feat(packager): always show command output, enhance formatting

---

.changes/pr246.md
crates/packager/src/package/app/mod.rs

Thanks for this fantastic crate! We're starting to use it for packaging up some Project Robius applications.
This PR fixes a minor mistake where the notarization credentials specified via environment variables are not used if a macos-specific config (`[package.metadata.packager.macos]`) has been specified in the `Cargo.toml`, but that config section _doesn't_ include the `notification_credentials` field.
Currently there is another related bug in the schema parsing that doesn't actually allow you to provide the `notarization_credentials` in the package metadata of Cargo.toml, so this change is actually the only way to currently use the notarization features on macOS, as far as I can tell.
More specifically, when I attempt to specify the `notarization_credentials` field in …

Support using env vars for macOS notarization even if a macOS config exists

---

.changes/pr255.md
crates/packager/src/config/mod.rs

New users may be confused when looking at the docs for `Config` and other config-like structs, as some fields cannot be specified in config files or via Cargo's package metadata.
This commit clarifies that those fields are intentionally excluded.
Also added an example of a macOS developer signing identity.
I added this notice to the docs of only 3 fields, those that were annotated with `#[serde(skip)]`. Let me know if there are any other fields that should have this notice too.

docs(macos): explicitly mention which fields are skipped

---

.changes/pr254.md
bindings/packager/nodejs/schema.json
crates/packager/schema.json
crates/packager/src/config/mod.rs
crates/packager/src/package/deb/mod.rs
crates/packager/src/package/pacman/mod.rs

This makes it possible to dynamically generate the list of dependencies for Linux Debian and pacman package formats. 
Fixed a small documentation bug in `PacmanConfig`.
We needed this feature in Project Robius to relieve the app dev from the burdens of:
1. figuring out which dependencies their app binaries need.
2. having to keep that list up to date when adding or removing dependencies from their app, which typically is only done at the Rust crate level (rather than the Linux native package/library level).
This changeset has been tested to work for us on Ubuntu LTS 20.04, 22.04, and 24.04, on both aarch64 and x86_64.
Question: I modified the `crates/packager/schema.json` file by hand -- not sure if that's correct or if it's generated automatically. It appears that …

feat: allow Linux dependencies to be specified via a file path

---

.changes/fix-dmg-failed-with-out-dir.md
crates/packager/src/config/mod.rs
crates/packager/src/util.rs

When `out-dir` is provided but does not exist, `create_icns_file()` returns a relative path (out/dir/icon.icns). Calling the `create-dmg` script will change the working dir to `out-dir`. When copying the volume icon, the icon does not exist at the path (out/dir/out/dir/icon.icns).

fix(dmg): canonicalize path returns from `create_icns_file`

---

README.md

Relative URLs are broken on https://crates.io/crates/cargo-packager. This replaces the URL with a full one.

chore: point to full URL in img

---

.changes/fix-nsis-resources-cross-compiling.md
crates/packager/src/package/nsis/mod.rs

pulling a fix in the tauri bundler that we did not port yet

fix(nsis): resources paths when cross compiling

---

.changes/pr_264.md
crates/packager/src/package/pacman/mod.rs

This ensures that paths with spaces on the target machine are properly preserved during pacman's installation of the package.
Context: some users of our Moxin app that was packaged for Arch Linux using `cargo-packager` reported that their pacman install command was failing due to paths containing whitespace.
Thanks to @cassaundra for proposing this fix and confirming that it works.

fix(pacman): enclose directory paths in `PKGBUILD` in double quotes

---

.changes/appimage-spaces.md
crates/packager/src/config/category.rs
crates/packager/src/config/mod.rs
crates/packager/src/package/appimage/mod.rs

ref https://github.com/tauri-apps/tauri/pull/11218

fix(packager): rename main bin name for AppImage if it has spaces

---

.changes/macos-background-app.md
bindings/packager/nodejs/schema.json
bindings/packager/nodejs/src-ts/config.d.ts
crates/packager/schema.json
crates/packager/src/config/mod.rs
crates/packager/src/package/app/mod.rs

Adds a new config setting for `background-app` specific to macOS that sets [LSUIElement](https://developer.apple.com/documentation/bundleresources/information-property-list/lsuielement) to true in the Info.plist.
This tells macOS the app is an "agent" app and is to run in the background with no icon in the Dock - particularly useful for menubar based apps that have no main window.
Have validated this works locally. Hopefully I have updated everything required!

feat(macos): add background-app configuration to support LSUIElement in Info.plist

---

.changes/disable-desktop-entry.md
bindings/packager/nodejs/schema.json
crates/packager/schema.json
crates/packager/src/config/mod.rs
crates/packager/src/package/app/mod.rs
crates/packager/src/package/deb/mod.rs

- CLI applications do not need to have desktop entries.
- Additionally, this should also help applications that want to use their own Desktop entries for all the packages.
- Currently, there seems to be an option to specify custom desktop entry template in debconfig, but not appimage and pacman. 
- By using this option, it should be possible to just use their own destkop entry as a normal package file.

feat: add config option to disable linux desktop entry

---

deny.toml

from what i saw in discussions Unicode-3.0 seems to be the same or really similar to Unicode-DFS-2016 which we already allow. please double check this yourself though, all that license speak is way over my head.

ci(deny): Allow Unicode-3.0 license

---

.changes/update-appimage-plugin.md
.github/workflows/build-examples.yml
crates/packager/src/package/appimage/mod.rs
deny.toml

closes #361
like in tauri i'd rather not touch linuxdeploy as a whole at the moment but this should work for this repo at least. i also plan to drop the use of linuxdeploy here in favor of sharun in the future, ref https://github.com/tauri-apps/tauri/pull/12491

fix(linux): pull latest linuxdeploy appimage plugin

---

.changes/notarize-keychain.md
crates/packager/src/codesign/macos.rs
crates/packager/src/config/mod.rs

This allows `notarytool` to use an Apple ID, Team ID and app-specific password stored in the keychain, by just providing the keychain profile as an env var (`"APPLE_KEYCHAIN_PROFILE"`). This reduces the number of env vars needed, and means the password isn't in a variable as plain text.
This approach is described under "Upload your app to the notarization service" here: https://developer.apple.com/documentation/security/customizing-the-notarization-workflow
Resolves #352

Add a `MacOsNotarizationCredentials` variant to use a keychain profile for notarytool settings and password.

---

.changes/fix-nsis-file-associations.md
crates/packager/src/package/nsis/installer.nsi

This allows file associations to be generated in `.nsi` files, and therefore in the final NSIS installer.
Fixes #364

Change nsi template from using `association.ext` to `association.extensions`, to match struct field in `FileAssociation`.
